services:
  frontend:
    container_name: allfuneral-frontend-dev
    image: allfuneral-frontend-dev
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./:/app